services:
  pihole:
    container_name: piholev6
    image: pihole/pihole:latest
    restart: unless-stopped
    hostname: piholev6
    networks:
      - traefik-network
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "4433:443/tcp" #-> access the admin dashboard on <ip-address>:4433/admin if traefik labels removed
    environment:
      - TZ=${TZ}
      - FTLCONF_webserver_api_password=${PIHOLE_PASSWORD}
      - FTLCONF_dns_listeningMode=${FTLCONF_dns_listeningMode}
      - FTLCONF_dns_upstreams=${FTLCONF_dns_upstreams}
      - FTLCONF_misc_etc_dnsmasq_d=${FTLCONF_misc_etc_dnsmasq_d}
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.tls=true
      - traefik.http.routers.pihole.rule=Host(`pihole.hobozzzx.live`)
      - traefik.http.routers.pihole.entrypoints=websecure
      - traefik.http.services.pihole.loadbalancer.server.port=80
      # Redirect root to /admin
      - "traefik.http.routers.pihole.middlewares=pihole-redirect-to-admin"
      - "traefik.http.middlewares.pihole-redirect-to-admin.redirectregex.regex=^https?://pihole.hobozzzx.live/$"
      - "traefik.http.middlewares.pihole-redirect-to-admin.redirectregex.replacement=https://pihole.hobozzzx.live/admin/"
      - "traefik.http.middlewares.pihole-redirect-to-admin.redirectregex.permanent=true"  # Make the redirect permanent
    volumes:
      - ./etc/pihole:/etc/pihole
      - ./etc/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - SYS_NICE
    env_file: .env
    depends_on:
      unbound:
        condition: service_healthy
  unbound:
    container_name: unbound
    image: mvance/unbound-rpi:latest
    restart: unless-stopped
    networks:
      - traefik-network
    volumes:
      - ./unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf # This is a file
      - ./unbound/unbound.conf.d:/opt/unbound/etc/unbound/unbound.conf.d # This should be a folder
      - ./logs/unbound.log:/opt/unbound/etc/unbound/unbound.log
      - ./root/named.root:/var/lib/unbound/root.hints
    #ports:
    #  - "5335:53/tcp" #ports not needed when using docker networking as its on same network as pihole
    #  - "5335:53/udp"
    healthcheck:
      test: ["CMD-SHELL", "drill @127.0.0.1 -p 5335 cloudflare.com || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
networks:
  traefik-network:
    external: true