---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    label: Raspberry Pi 4
    cpu: true
    memory: true
    disk: /
    cputemp: true
    uptime: true
    units: metric
    refresh: 3000

- search:
    provider: [google, duckduckgo]
    target: _blank
    focus: true
    showSearchSuggestions: true

- datetime:
    locale: en
    text_size: xl
    format:
      timeStyle: medium
      dateStyle: medium

- openmeteo:
    label: "{{HOMEPAGE_VAR_OPENMETEO_LABEL}}" # optional
    latitude: "{{HOMEPAGE_VAR_OPENMETEO_LAT}}"
    longitude: "{{HOMEPAGE_VAR_OPENMETEO_LON}}"
    timezone: "{{HOMEPAGE_VAR_TIMEZONE}}" # optional
    units: metric
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
